#:schema node_modules/wrangler/config-schema.json
name = "mamad"
main = "src/index.js"
compatibility_date = "2026-09-12"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]

# vless uuid
UUID = ""

# cloudflare reverse proxy
PROXY = ""

# WebSocket transport URL path
WS_PATH = ""

# XHTTP transport URL path
XHTTP_PATH = ""

